  name: Backport Assistant Runner
  
  on:
    pull_request_target:
      types:
        - closed
  
  jobs:
    backport:
      if: github.event.pull_request.merged
      runs-on: ubuntu-latest
      container: hashicorpdev/backport-assistant:0.2.2
      steps:
        - name: Run Backport Assistant for release branches
          run: |
            backport-assistant backport
          env:
            BACKPORT_LABEL_REGEXP: "backport/(?P<target>\\d+\\.\\d+\\.\\w+)"
            BACKPORT_TARGET_TEMPLATE: "release/{{.target}}"
            GITHUB_TOKEN: ${{ secrets.SARAH_ACTIONS_PAT }}