name: update-master-flow

on:
  push:
    tags:        
      - 'v*'

jobs:
  minor-tag:
    if: github.event.base_ref == 'refs/heads/main' || startsWith(github.event.base_ref,'refs/heads/release/') != false
    runs-on: ubuntu-latest
    steps:
    - name: Get the tag version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - uses: actions/go-update-mod-dependencies@v1
      id: update-vault
      env:
        GOPRIVATE: "github.com/hashicorp/*"
        GITHUB_TOKEN: ${{ secrets.SARAH_ACTIONS_PAT }}
        VERSION: ${{ steps.get_version.outputs.VERSION }}
        ACTOR: ${{ github.event.head_commit.author.username }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        branch: 'master'
        update-strategy: 'latest'
        target-repo: 'github.com/sarahethompson/vault'
    - name: Slack failure
      uses: act10ns/slack@v1
      id: slack-failure
      if: failure()
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        status: ${{ job.status }}
